### ISSUE TITLE
Questions regarding the unsupervised image2image translation baselines reported in the paper. 

### ISSUE THREAD

**Issue by boqchen** [lifangda01/AdaptiveSupervisedPatchNCE#7]
Hi Fangda,

Thanks for the great work!

I have some questions about the unsupervised image-to-image translation baselines, namely CycleGAN and CUT, reported in the paper (Table 1). I was wondering if these methods are trained with paired data, or you organized the data in a unpaired fashion (e.g., by randomly shuffling) for these baselines. If it is trained with paired data, what is the logic behind it, since these methods are originally proposed for the unpaired setting. Also I noticed that only CUT trained with a supervised loss (i.e., the Gaussian Pyramid L1 loss) is reported, did you also test the original CUT model with only the contrastive loss?

Thanks for you time and consideration!

Best regards,
Boqi

**Comment by lifangda01** [comment]
Hello,

- For both CycleGAN and CUT, I used the paired data to keep the data loading process the same across all methods. I don't remember seeing big differences between using unpaired and paired data in the case of CycleGAN.
- I did try the original CUT with unpaired data and without the additional L1 loss in my early experiments. Again, as far as I can recall, I decided to report with paired CUT with supervised loss because it performed better.

Hope this helps!

Fangda

**Comment by boqchen** [comment]
Hi Fangda, 

Thanks for your prompt reply.

I am still wondering what is the ​rationale behind using unsupervised image translation methods on paired data. In the [BCI paper](https://arxiv.org/pdf/2204.11425v1.pdf), the authors argue "... cycleGAN ... can only achieve “style” migration, but it
is completely impossible to identify the cancer areas ...". I am wondering if you observe similar results that when translating H&E into functional stains, these unsupervised image translation methods achieves merely "style transfer", rather than highlight the areas where the targeting proteins are.

Thanks!

**Comment by lifangda01** [comment]
I agree with you that unsupervised image translation methods may not be suitable for translation into functional stains, since what they achieve is the transfer of likeness. Nevertheless, due to the very fact that they are unsupervised, they are free from the GT inconsistencies, which are known to cause problems in many off-the-shelf supervised methods. Therefore, they still serve some value in the experimental comparisons.

**Comment by boqchen** [comment]
Hi Fangda,

Thanks for the insights! It helps a lot!

Best,
Boqi
